name: dartdoc_autobuild
description:
  The service lets you automatically build dart docs on every github repository push merge pull request.
version: 0.0.1
homepage: https://github.com/alexd1971/dartdoc_autobuild
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  shelf: ^0.7.3
  meta: ^1.1.6
  html: ^0.13.3

dev_dependencies:
 test: ^1.3.0
